name: Trigger auto deployment for database-ms

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '.github/workflows/database-ms-AutoDeployTrigger-99c15cd5-12b9-4e44-92d1-13b721521bdb.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DATABASEMS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DATABASEMS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DATABASEMS_AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.DATABASEMS_REGISTRY_PASSWORD }}" | docker login ${{ secrets.DATABASEMS_REGISTRY_URL }} \
            --username "${{ secrets.DATABASEMS_REGISTRY_USERNAME }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DATABASEMS_REGISTRY_URL }}/database-ms:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DATABASEMS_REGISTRY_URL }}/database-ms:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name database-ms \
            --resource-group proeto-ia \
            --image ${{ secrets.DATABASEMS_REGISTRY_URL }}/database-ms:${{ github.sha }}
